-- MySQL Script generated by MySQL Workbench
-- Sat 01 Dec 2018 07:16:30 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema news
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema news
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
SHOW WARNINGS;
USE `news` ;

-- -----------------------------------------------------
-- Table `news`.`n_information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_information` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_information` (
  `info_id` VARCHAR(40) NOT NULL COMMENT '资讯ID',
  `info_title` VARCHAR(255) NULL COMMENT '资讯标题',
  `info_show_style` CHAR(1) NULL COMMENT '资讯展示风格0大图1右侧小图2图集',
  `info_index_image_path` VARCHAR(255) NULL COMMENT '资讯列表图片路径',
  `info_content` TEXT NULL COMMENT '资讯正文',
  `info_is_top` CHAR(1) NULL DEFAULT 0 COMMENT '是否置顶，0不置顶1置顶',
  `info_publisher` VARCHAR(40) NULL COMMENT '资讯发布者',
  `info_own_channel` VARCHAR(40) NULL COMMENT '所属频道',
  `info_share_num` BIGINT(20) NULL COMMENT '资讯分享数量',
  `info_like_num` BIGINT(20) NULL COMMENT '资讯点赞数量',
  `info_download_num` BIGINT(20) NULL COMMENT '资讯下载数量',
  `info_status` CHAR(1) NULL DEFAULT 0 COMMENT '0未审核1一审通过2二审通过',
  `info_audit_time_one` DATETIME NULL COMMENT '资讯一审通过时间',
  `info_audit_user_one` VARCHAR(40) NULL COMMENT '资讯一审审核人',
  `info_audit_time_two` DATETIME NULL COMMENT '资讯二审通过时间',
  `info_audit_user_two` VARCHAR(40) NULL COMMENT '资讯二审审核人',
  `info_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '资讯创建时间',
  `info_create_user` VARCHAR(40) NULL COMMENT '资讯创建人',
  `info_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '资讯更新时间',
  `info_update_user` VARCHAR(45) NULL COMMENT '资讯更新人',
  `info_version` BIGINT(20) NULL COMMENT '资讯版本号',
  `info_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  PRIMARY KEY (`info_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '资讯表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_information_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_information_image` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_information_image` (
  `image_id` VARCHAR(40) NOT NULL COMMENT '图片ID',
  `publisher_id` VARCHAR(40) NULL COMMENT '资讯发布者主键',
  `image_file_path` VARCHAR(255) NULL COMMENT '图片文件路径',
  `image_upload_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '资讯正文图片上传时间',
  `image_upload_user` VARCHAR(40) NULL COMMENT '资讯正文图片上传人',
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '资讯图片表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_information_publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_information_publisher` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_information_publisher` (
  `publisher_id` VARCHAR(40) NOT NULL COMMENT '资讯发布者主键',
  `publisher_name` VARCHAR(40) NULL COMMENT '发布者名字',
  `publisher_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布者创建时间',
  `publisher_create_user` VARCHAR(40) NULL COMMENT '发布者创建人',
  `publisher_photo_image` VARCHAR(255) NULL COMMENT '发布者头像',
  `publish_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发布者更新时间',
  `publisher_update_user` VARCHAR(40) NULL COMMENT '发布者更新人',
  `publisher_is_delete` CHAR(1) NULL COMMENT '是否删除0未删除1删除',
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '资讯发布者表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_reporter_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_reporter_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_reporter_info` (
  `reporter_id` VARCHAR(40) NOT NULL COMMENT '记者主键',
  `reporter_name` VARCHAR(40) NULL COMMENT '记者名字',
  `reporter_own_media` VARCHAR(40) NULL COMMENT '所属媒体',
  `reporter_own_media_name` VARCHAR(255) NULL COMMENT '所属媒体名字',
  `reporter_phone_num` VARCHAR(11) NULL COMMENT '手机号码',
  `reporter_title` VARCHAR(40) NULL COMMENT '记者职位',
  `reporter_birthday` DATE NULL COMMENT '记者出生日期',
  `reporter_clothes_size` CHAR(1) NULL COMMENT '记者衣服尺码0XS1S2M3L4XL5XXL6XXXL',
  `reporter_driving_licence` INT NULL COMMENT '记者驾龄',
  `reporter_level` CHAR(1) NULL COMMENT '记者级别1I2II3III4IV5V',
  `reporter_email` VARCHAR(255) NULL COMMENT '记者邮箱',
  `reporter_zip_code` VARCHAR(6) NULL COMMENT '邮政编码',
  `reporter_gender` CHAR(1) NULL COMMENT '记者性别0女1男',
  `reporter_work_tel` VARCHAR(40) NULL COMMENT '工作座机',
  `reporter_identity_num` VARCHAR(18) NULL COMMENT '身份证号码',
  `reporter_passport_num` VARCHAR(11) NULL COMMENT '媒体记者护照号码',
  `reporter_home_address` VARCHAR(255) NULL COMMENT '家庭住址',
  `reporter_is_have_child` CHAR(1) NULL COMMENT '是否有孩子0无1有3不清楚',
  `reporter_child_gender` CHAR(1) NULL COMMENT '孩子性别0女孩1男孩',
  `reporter_child_birthday` DATE NULL COMMENT '孩子生日',
  `reporter_second_child_gender` CHAR(1) NULL COMMENT '二孩性别0女孩1男孩',
  `reporter_second_child_birthday` DATE NULL COMMENT '二孩生日',
  `reporter_other_info` VARCHAR(400) NULL COMMENT '记者其他信息',
  PRIMARY KEY (`reporter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '媒体记者信息表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_media` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_media` (
  `media_id` VARCHAR(40) NOT NULL COMMENT '媒体主键',
  `media_level` VARCHAR(40) NULL COMMENT '媒体级别',
  `media_region` VARCHAR(40) NULL COMMENT '媒体区域',
  `media_city` VARCHAR(40) NULL COMMENT '媒体所属城市',
  `media_name` VARCHAR(255) NULL COMMENT '媒体名字',
  `media_type` VARCHAR(40) NULL COMMENT '媒体类型',
  `media_category` VARCHAR(40) NULL COMMENT '媒体类别',
  `media_group` VARCHAR(255) NULL COMMENT '所属媒体集团',
  `media_page` VARCHAR(40) NULL COMMENT '媒体版面',
  `media_channel` VARCHAR(40) NULL COMMENT '媒体频道',
  `media_is_important` CHAR(1) NULL DEFAULT 0 COMMENT '是否为重要媒体0不重要1重要',
  `media_is_dispatch` CHAR(1) NULL DEFAULT 0 COMMENT '是否允许发稿0不允许1允许',
  `media_logo_image` VARCHAR(255) NULL COMMENT '媒体标志图片',
  `media_contact_address` VARCHAR(255) NULL COMMENT '媒体联系地址',
  `media_contact_tel` VARCHAR(40) NULL COMMENT '媒体联系电话',
  `media_create_user` VARCHAR(40) NULL COMMENT '记录创建人',
  `media_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `media_update_user` VARCHAR(40) NULL COMMENT '记录更新人',
  `media_update_time` DATETIME NULL COMMENT '记录更新时间',
  `media_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  PRIMARY KEY (`media_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '媒体表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity` (
  `activity_id` VARCHAR(40) NOT NULL COMMENT '活动ID',
  `activity_name` VARCHAR(255) NULL COMMENT '活动名称',
  `activity_start_time` DATETIME NULL COMMENT '活动开始时间',
  `activity_end_time` DATETIME NULL COMMENT '活动结束时间',
  `activity_status` CHAR(1) NULL COMMENT '活动状态0未开始1正在进行2已经结束',
  `activity_brochure_image` VARCHAR(40) NULL COMMENT '活动封面图片',
  `activity_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '活动创建时间',
  `activity_create_user` VARCHAR(40) NULL COMMENT '活动创建人',
  `activity_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '活动更新时间',
  `activity_update_user` VARCHAR(40) NULL COMMENT '活动更新人',
  `activity_remark` VARCHAR(500) NULL COMMENT '活动备注',
  `activity_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  `activity_version` BIGINT(20) NULL DEFAULT 0 COMMENT '活动版本号',
  PRIMARY KEY (`activity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_iamge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_iamge` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_iamge` (
  `image_id` VARCHAR(40) NOT NULL COMMENT '活动图片主键',
  `activity_id` VARCHAR(40) NULL COMMENT '活动主键',
  `image_file_path` VARCHAR(255) NULL COMMENT '图片文件路径',
  `image_upload_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '图片上传时间',
  `image_upload_user` VARCHAR(40) NULL COMMENT '图片上传人',
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动图片表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_news` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_news` (
  `news_id` VARCHAR(40) NOT NULL COMMENT '新闻稿ID',
  `activity_id` VARCHAR(40) NULL COMMENT '活动ID',
  `news_title` VARCHAR(255) NULL COMMENT '新闻稿标题',
  `news_content` TEXT NULL COMMENT '新闻稿内容',
  `news_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新闻稿创建时间',
  `news_create_user` VARCHAR(40) NULL COMMENT '新闻稿创建用户',
  `news_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '新闻稿更新时间',
  `news_update_user` VARCHAR(40) NULL COMMENT '新闻稿更新用户',
  `news_is_audit` CHAR(1) NULL DEFAULT 0 COMMENT '新闻稿是否审核0未审核1一审2二审',
  `news_audit_user_one` VARCHAR(40) NULL COMMENT '新闻稿一审用户',
  `news_audit_time_one` DATETIME NULL COMMENT '新闻稿一审时间',
  `news_audit_user_two` VARCHAR(40) NULL COMMENT '新闻稿二审用户',
  `news_audit_time_two` DATETIME NULL COMMENT '新闻稿二审时间',
  `news_is_crontab` CHAR(1) NULL DEFAULT 0 COMMENT '是否定时发送0不定时1定时',
  `news_cron_time` DATETIME NULL COMMENT '定时发送时间',
  `news_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  `news_like_num` BIGINT(20) NULL DEFAULT 0 COMMENT '新闻稿点赞数量',
  `news_share_num` BIGINT(20) NULL DEFAULT 0 COMMENT '新闻稿分享数量',
  `news_download_num` BIGINT(20) NULL DEFAULT 0 COMMENT '新闻稿下载数量',
  `news_version` BIGINT(20) NULL DEFAULT 0 COMMENT '新闻稿版本',
  PRIMARY KEY (`news_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动新闻稿表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_group` (
  `group_id` VARCHAR(40) NOT NULL COMMENT '活动媒体分组主键',
  `activity_id` VARCHAR(40) NULL COMMENT '活动ID',
  `group_name` VARCHAR(40) NULL COMMENT '分组名字',
  `reporter_id` VARCHAR(40) NULL COMMENT '媒体记者ID',
  `reporter_name` VARCHAR(40) NULL COMMENT '媒体记者名字',
  `media_id` VARCHAR(40) NULL COMMENT '媒体记者所属媒体ID',
  `media_name` VARCHAR(255) NULL COMMENT '媒体接着所属媒体名字',
  `group_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '分组创建时间',
  `group_create_user` VARCHAR(40) NULL COMMENT '分组创建人',
  `group_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '分组更新时间',
  `group_update_user` VARCHAR(40) NULL COMMENT '分组更新人',
  `group_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  `group_is_useable` CHAR(1) NULL DEFAULT '1' COMMENT '分组是否可用',
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动分组表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_notify`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_notify` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_notify` (
  `notify_id` VARCHAR(40) NOT NULL COMMENT '活动通知ID',
  `acvitity_id` VARCHAR(40) NULL COMMENT '活动ID',
  `notify_content` VARCHAR(500) NULL COMMENT '通知内容',
  `notify_send_object` CHAR(1) NULL COMMENT '通知发送对象0所有参加活动的记者1某个记者分组2单个记者',
  `notify_is_crontab` CHAR(1) NULL COMMENT '是否定时发送0不定时1定时',
  `notify_send_time` DATETIME NULL COMMENT '发送时间',
  `notify_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '活动通知创建时间',
  `notify_create_user` VARCHAR(40) NULL COMMENT '活动通知创建人',
  `notify_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '活动通知更新时间',
  `notify_update_user` VARCHAR(40) NULL COMMENT '活动通知更新人',
  `notify_version` BIGINT(20) NULL COMMENT '活动通知版本号',
  PRIMARY KEY (`notify_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动通知表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_media` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_media` (
  `activity_id` VARCHAR(40) NULL COMMENT '活动ID',
  `reporter_id` VARCHAR(40) NULL COMMENT '活动受邀记者ID',
  `reporter_name` VARCHAR(40) NULL COMMENT '活动受邀记者名称',
  `media_id` VARCHAR(40) NULL COMMENT '媒体ID',
  `media_name` VARCHAR(255) NULL COMMENT '媒体名称',
  `reporter_is_invitation` CHAR(1) NULL COMMENT '是否发送邀请0未发送1已发送',
  `reporter_invitation_time` DATETIME NULL COMMENT '发送邀请时间',
  `reporter_response_time` DATETIME NULL COMMENT '媒体记者回应时间',
  `reporter_response_result` CHAR(1) NULL COMMENT '媒体记者回应结果0本人参加1他人参加2不参加',
  `reporter_response_remark` VARCHAR(255) NULL COMMENT '媒体记者回应备注',
  `reporter_response_update_time` DATETIME NULL COMMENT '媒体记者回应结果更新时间',
  `reporter_response_update_user` VARCHAR(40) NULL COMMENT '媒体记者回应结果更新人',
  `reporter_is_sign` CHAR(1) NULL DEFAULT 0 COMMENT '媒体记者签到标识0未签到1已签到',
  `reporter_sign_time` DATETIME NULL COMMENT '媒体记者签到时间')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动邀请媒体表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_activity_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_activity_invitation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_activity_invitation` (
  `invitation_id` VARCHAR(40) NULL COMMENT '邀请函ID',
  `activity_id` VARCHAR(40) NULL COMMENT '活动ID',
  `invitation_title` VARCHAR(255) NULL COMMENT '邀请函标题',
  `invitation_content` TEXT NULL COMMENT '邀请函正文',
  `invitation_create_user` VARCHAR(40) NULL COMMENT '邀请函创建人',
  `invitation_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '邀请函创建时间',
  `invitation_update_user` VARCHAR(40) NULL COMMENT '邀请函更新人',
  `invitation_update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '邀请函更新时间',
  `invitation_is_delete_copy1` CHAR(1) NULL DEFAULT '1' COMMENT '是否可用0不可用1可用',
  `invitation_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  `invitation_version` BIGINT(20) NULL COMMENT '邀请函版本号')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '活动邀请函表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_news_bulletin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_news_bulletin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_news_bulletin` (
  `bulletin_id` VARBINARY(40) NULL COMMENT '简报主键',
  `bulletin_media_type` VARCHAR(40) NULL COMMENT '简报媒体类型',
  `bulletin_media_name` VARCHAR(255) NULL COMMENT '简报媒体名字',
  `bulletin_reporter_id` VARCHAR(40) NULL COMMENT '简报作者',
  `bulletin_reporter_name` VARCHAR(40) NULL COMMENT '简报作者名字',
  `bulletin_publish_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '简报发布时间',
  `bulletin_word_num` INT NULL COMMENT '简报字数',
  `bulletin_page` VARCHAR(40) NULL COMMENT '简报版面',
  `bulletin_level` VARCHAR(40) NULL COMMENT '简报级别',
  `bulletin_title` VARCHAR(255) NULL COMMENT '简报标题',
  `bulletin_url` VARCHAR(255) NULL COMMENT '简报url',
  `bulletin_tone` VARCHAR(255) NULL COMMENT '简报标签',
  `bulletin_share_num` BIGINT(20) NULL COMMENT '简报分享数量',
  `bulletin_create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '简报创建时间',
  `bulletin_create_user` VARCHAR(40) NULL COMMENT '简报创建人',
  `bulletin_update_time` DATETIME NULL COMMENT '简报更新时间',
  `bulletin_update_user` VARCHAR(40) NULL COMMENT '简报更新人',
  `bulletin_is_delete` CHAR(1) NULL DEFAULT 0 COMMENT '是否删除0未删除1删除',
  `bulletin_version` BIGINT(20) NULL COMMENT '简报版本号')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '新闻简报表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `news`.`n_register_reporter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news`.`n_register_reporter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `news`.`n_register_reporter` (
  `reporter_id` VARCHAR(40) NOT NULL COMMENT '记者主键',
  `reporter_name` VARCHAR(40) NULL COMMENT '记者名字',
  `reporter_own_media` VARCHAR(40) NULL COMMENT '所属媒体',
  `reporter_own_media_name` VARCHAR(255) NULL COMMENT '所属媒体名字',
  `reporter_is_access` CHAR(1) NULL COMMENT '是否通过认证0未认证1认证',
  `reporter_access_time` DATETIME NULL COMMENT '通过认证时间',
  `reporter_registry_time` DATETIME NULL COMMENT '注册时间',
  `reporter_last_login_time` DATETIME NULL COMMENT '最后登陆时间',
  `reporter_birthday` DATE NULL COMMENT '记者出生日期',
  `reporter_clothes_size` CHAR(1) NULL COMMENT '记者衣服尺码0XS1S2M3L4XL5XXL6XXXL',
  `reporter_driving_licence` INT NULL COMMENT '记者驾龄',
  `reporter_level` CHAR(1) NULL COMMENT '记者级别1I2II3III4IV5V',
  `reporter_audit_time` DATETIME NULL COMMENT '审核时间',
  `reporter_audit_user_id` VARCHAR(40) NULL COMMENT '审核结果0未审核1审核通过2审核不通过',
  `reporter_audit_user_name` VARCHAR(40) NULL COMMENT '审核结果0未审核1审核通过2审核不通过',
  `reporter_audit_result` CHAR(1) NULL COMMENT '审核结果0未审核1审核通过2审核不通过',
  `reporter_phone_num` VARCHAR(11) NULL COMMENT '手机号码',
  `reporter_title` VARCHAR(40) NULL COMMENT '记者职位',
  `reporter_email` VARCHAR(255) NULL COMMENT '记者邮箱',
  `reporter_zip_code` VARCHAR(6) NULL COMMENT '邮政编码',
  `reporter_gender` CHAR(1) NULL COMMENT '记者性别0女1男',
  `reporter_work_tel` VARCHAR(40) NULL COMMENT '工作座机',
  `reporter_work_cert` VARCHAR(255) NULL COMMENT '工作证明',
  `reporter_identity_num` VARCHAR(18) NULL COMMENT '身份证号码',
  `reporter_passport_num` VARCHAR(11) NULL COMMENT '媒体记者护照号码',
  `reporter_home_address` VARCHAR(255) NULL COMMENT '家庭住址',
  `reporter_is_have_child` CHAR(1) NULL COMMENT '是否有孩子0无1有',
  `reporter_child_gender` CHAR(1) NULL COMMENT '孩子性别0女孩1男孩',
  `reporter_child_birthday` DATE NULL COMMENT '孩子生日',
  `reporter_second_child_gender` CHAR(1) NULL COMMENT '二孩性别0女孩1男孩',
  `reporter_second_child_birthday` DATE NULL COMMENT '二孩生日',
  `reporter_other_info` VARCHAR(400) NULL COMMENT '记者其他信息',
  `reporter_phone_flag` CHAR(1) NULL COMMENT '记者手机号是否一致0不一致1一致',
  PRIMARY KEY (`reporter_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '媒体记者注册表';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
